version: '3.8'

services:
  etsweatherproject:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - ../.env
    command: python src/main.py
    ports:
      - "8000:8000"
    volumes:
      - ./ETSweatherproject/BBDD:/app/ETSweatherproject/BBDD

volumes:
  db_data:
